SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS Narudzba;
DROP TABLE IF EXISTS Osoba;
DROP TABLE IF EXISTS Razina_Prava;
DROP TABLE IF EXISTS Status_Narudzbe;
DROP TABLE IF EXISTS Nacin_Placanja;
DROP TABLE IF EXISTS Tecaj;
DROP TABLE IF EXISTS Ocjene_tecaja;
DROP TABLE IF EXISTS Videozapisi;