// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WAZOT.DataAccess;

#nullable disable

namespace WAZOT.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220509143135_allmigrations")]
    partial class allmigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WAZOT.Models.Nacin_placanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NacinPlacanja");
                });

            modelBuilder.Entity("WAZOT.Models.Narudzba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Nacin_placanjaId")
                        .HasColumnType("int");

                    b.Property<string>("OsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Stats_narudzbeId")
                        .HasColumnType("int");

                    b.Property<int>("TecajId")
                        .HasColumnType("int");

                    b.Property<long>("datum_pocetak")
                        .HasColumnType("bigint");

                    b.Property<long>("datum_zavrsetak")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Nacin_placanjaId");

                    b.HasIndex("OsobaOib");

                    b.HasIndex("Stats_narudzbeId");

                    b.HasIndex("TecajId");

                    b.ToTable("Narudzba");
                });

            modelBuilder.Entity("WAZOT.Models.Ocjena_tecaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TecajId")
                        .HasColumnType("int");

                    b.Property<string>("komentar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ocjena")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OsobaOib");

                    b.HasIndex("TecajId");

                    b.ToTable("OcjeneTecaja");
                });

            modelBuilder.Entity("WAZOT.Models.Osoba", b =>
                {
                    b.Property<string>("Oib")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Razina_PravaId")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Oib");

                    b.HasIndex("Razina_PravaId");

                    b.ToTable("Osoba");
                });

            modelBuilder.Entity("WAZOT.Models.Razina_Prava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Razina_Prava");
                });

            modelBuilder.Entity("WAZOT.Models.Status_narudzbe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Status_Narudzbe");
                });

            modelBuilder.Entity("WAZOT.Models.Tecaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("prosjecna_ocjena")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("OsobaOib");

                    b.ToTable("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Videozapis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TecajId")
                        .HasColumnType("int");

                    b.Property<string>("videozapis_putanja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("videozapis_tip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TecajId");

                    b.ToTable("Videozapis");
                });

            modelBuilder.Entity("WAZOT.Models.Narudzba", b =>
                {
                    b.HasOne("WAZOT.Models.Nacin_placanja", "Nacin_placanja")
                        .WithMany()
                        .HasForeignKey("Nacin_placanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Status_narudzbe", "Stats_narudzbe")
                        .WithMany()
                        .HasForeignKey("Stats_narudzbeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nacin_placanja");

                    b.Navigation("Osoba");

                    b.Navigation("Stats_narudzbe");

                    b.Navigation("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Ocjena_tecaja", b =>
                {
                    b.HasOne("WAZOT.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");

                    b.Navigation("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Osoba", b =>
                {
                    b.HasOne("WAZOT.Models.Razina_Prava", "Razina_Prava")
                        .WithMany()
                        .HasForeignKey("Razina_PravaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Razina_Prava");
                });

            modelBuilder.Entity("WAZOT.Models.Tecaj", b =>
                {
                    b.HasOne("WAZOT.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");
                });

            modelBuilder.Entity("WAZOT.Models.Videozapis", b =>
                {
                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecaj");
                });
#pragma warning restore 612, 618
        }
    }
}
