// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WAZOT.DataAccess;

#nullable disable

namespace WAZOT.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WAZOT.Models.Cjelina_tecaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("TecajId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("naziv_cjeline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("opis_cjeline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TecajId");

                    b.ToTable("CjelinaTecaja");
                });

            modelBuilder.Entity("WAZOT.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Kategorija");
                });

            modelBuilder.Entity("WAZOT.Models.Neprikladni_komentar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ocjena_tecajaId")
                        .HasColumnType("int");

                    b.Property<string>("PrijavaOsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("PrijavljenOsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("Ocjena_tecajaId");

                    b.HasIndex("PrijavaOsobaOib");

                    b.HasIndex("PrijavljenOsobaOib");

                    b.ToTable("NeprikladniKomentar");
                });

            modelBuilder.Entity("WAZOT.Models.Ocjena_tecaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Cjelina_tecajaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("OsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("TecajId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("komentar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ocjena")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cjelina_tecajaId");

                    b.HasIndex("OsobaOib");

                    b.HasIndex("TecajId");

                    b.ToTable("OcjeneTecaja");
                });

            modelBuilder.Entity("WAZOT.Models.Osoba", b =>
                {
                    b.Property<string>("Oib")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("Razina_PravaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("odobreno")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("pin")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Oib");

                    b.HasIndex("Razina_PravaId");

                    b.ToTable("Osoba");
                });

            modelBuilder.Entity("WAZOT.Models.Poruka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Datum_slanja")
                        .HasColumnType("bigint");

                    b.Property<string>("PosiljateljOsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int>("RazgovorId")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PosiljateljOsobaOib");

                    b.HasIndex("RazgovorId");

                    b.ToTable("Poruka");
                });

            modelBuilder.Entity("WAZOT.Models.Pracenje_Korisnika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<long>("Datum_posjete")
                        .HasColumnType("bigint");

                    b.Property<string>("OsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("TecajId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<long>("Vrijeme_videozapis")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsobaOib");

                    b.HasIndex("TecajId");

                    b.ToTable("Pracenje_Korisnika");
                });

            modelBuilder.Entity("WAZOT.Models.Prijava_Na_Tecaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("Status_PrijaveId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("TecajId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<long>("datum_pocetak")
                        .HasColumnType("bigint");

                    b.Property<long>("datum_zavrsetak")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OsobaOib");

                    b.HasIndex("Status_PrijaveId");

                    b.HasIndex("TecajId");

                    b.ToTable("PrijavaNaTecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Razgovor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PosiljateljOsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("PrimateljOsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("PosiljateljOsobaOib");

                    b.HasIndex("PrimateljOsobaOib");

                    b.ToTable("Razgovor");
                });

            modelBuilder.Entity("WAZOT.Models.Razina_Prava", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Razina_Prava");
                });

            modelBuilder.Entity("WAZOT.Models.Status_prijave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Status_Prijave");
                });

            modelBuilder.Entity("WAZOT.Models.Tecaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("KategorijaId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("OsobaOib")
                        .IsRequired()
                        .HasColumnType("varchar(11)");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("prosjecna_ocjena")
                        .HasColumnType("float");

                    b.Property<string>("slika")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.HasIndex("OsobaOib");

                    b.ToTable("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Videozapis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Cjelina_TecajaId")
                        .HasColumnType("int");

                    b.Property<int?>("TecajId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("videozapis_naziv")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("videozapis_putanja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("videozapis_tip")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Cjelina_TecajaId");

                    b.HasIndex("TecajId");

                    b.ToTable("Videozapis");
                });

            modelBuilder.Entity("WAZOT.Models.Cjelina_tecaja", b =>
                {
                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Neprikladni_komentar", b =>
                {
                    b.HasOne("WAZOT.Models.Ocjena_tecaja", "Ocjena_tecaja")
                        .WithMany()
                        .HasForeignKey("Ocjena_tecajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Osoba", "PrijavaOsoba")
                        .WithMany()
                        .HasForeignKey("PrijavaOsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Osoba", "PrijavljenOsoba")
                        .WithMany()
                        .HasForeignKey("PrijavljenOsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocjena_tecaja");

                    b.Navigation("PrijavaOsoba");

                    b.Navigation("PrijavljenOsoba");
                });

            modelBuilder.Entity("WAZOT.Models.Ocjena_tecaja", b =>
                {
                    b.HasOne("WAZOT.Models.Cjelina_tecaja", "Cjelina_tecaja")
                        .WithMany()
                        .HasForeignKey("Cjelina_tecajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cjelina_tecaja");

                    b.Navigation("Osoba");

                    b.Navigation("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Osoba", b =>
                {
                    b.HasOne("WAZOT.Models.Razina_Prava", "Razina_Prava")
                        .WithMany()
                        .HasForeignKey("Razina_PravaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Razina_Prava");
                });

            modelBuilder.Entity("WAZOT.Models.Poruka", b =>
                {
                    b.HasOne("WAZOT.Models.Osoba", "PosiljateljOsoba")
                        .WithMany()
                        .HasForeignKey("PosiljateljOsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Razgovor", "Razgovor")
                        .WithMany()
                        .HasForeignKey("RazgovorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosiljateljOsoba");

                    b.Navigation("Razgovor");
                });

            modelBuilder.Entity("WAZOT.Models.Pracenje_Korisnika", b =>
                {
                    b.HasOne("WAZOT.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");

                    b.Navigation("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Prijava_Na_Tecaj", b =>
                {
                    b.HasOne("WAZOT.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Status_prijave", "Status_prijave")
                        .WithMany()
                        .HasForeignKey("Status_PrijaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osoba");

                    b.Navigation("Status_prijave");

                    b.Navigation("Tecaj");
                });

            modelBuilder.Entity("WAZOT.Models.Razgovor", b =>
                {
                    b.HasOne("WAZOT.Models.Osoba", "PosiljateljOsoba")
                        .WithMany()
                        .HasForeignKey("PosiljateljOsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Osoba", "PrimateljOsoba")
                        .WithMany()
                        .HasForeignKey("PrimateljOsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PosiljateljOsoba");

                    b.Navigation("PrimateljOsoba");
                });

            modelBuilder.Entity("WAZOT.Models.Tecaj", b =>
                {
                    b.HasOne("WAZOT.Models.Kategorija", "Kategorija")
                        .WithMany()
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WAZOT.Models.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaOib")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Osoba");
                });

            modelBuilder.Entity("WAZOT.Models.Videozapis", b =>
                {
                    b.HasOne("WAZOT.Models.Cjelina_tecaja", "CjelinaTecaja")
                        .WithMany()
                        .HasForeignKey("Cjelina_TecajaId");

                    b.HasOne("WAZOT.Models.Tecaj", "Tecaj")
                        .WithMany()
                        .HasForeignKey("TecajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CjelinaTecaja");

                    b.Navigation("Tecaj");
                });
#pragma warning restore 612, 618
        }
    }
}
